name: Demo Continious integration
On: 
    push:
        branches:
          - main:
    pull request:
        branches:
          - main:

    schdule:
          - cron: '30 14 " " MON-FRI'
    jobs:
           build:
             runs-on: window-latest

           steps:
             - name: checkout to repository
               uses: actions/checkout@v3

             - name: Download and setup JDk
               uses: actions/setup-java@v3
               with:
                  java version: '11'
                  distributor: 'temurin'
                  continue-on-error: true

             - name: Download and setup maven
               uses: stcarolas/setup-maven@v4.4
               with:
                  maven-version:3.8.2

             - name: Build using maven
               run: mvn clean install

    test:
      needs: build
      runs-on: {{needs.build.output.runs.on}}
    steps:
           - name : run test
             run: mvn test "-Dcucumber.filter.tags=@smoke"
              env: 
                Display: :19
                CUCUMBER_PUBLISH_TOKEN: 26e445a8-1e62-4bbf-8b65-76f3cc18a217
                continue-on-error: true
              





               
         
